#!/bin/sh

CROSS=i686-elf-
CROSS_CC=${CROSS}gcc
CROSS_LD=${CROSS}ld
CROSS_AS=${CROSS}as


VERSION=0.1.0                              # in case this ever starts getting shared
GIT_HASH=$(git describe --dirty --always)  # very helpful for debugging
DATE_BUILT=$(date "+%Y-%m-%d %H:%M")       # decorational mainly

# support subsystems on/off, for easier debugging, smaller sizes etc.
GUI_SUPPORT=1       # support for graphics
USB_SUPPORT=1       # support for usb
NETWORK_SUPPORT=1   # support for network
SMP_SUPPORT=1       # support for SMP

# compilation mode
DEBUG_VERSION=0     # support for gdb, and other macros
HOSTED_FLAG=0       # build run for hosted linux, as opposed to standalone
ASSERTS=1           # whether asserts are run or ignored
LOG_LEVEL=INFO      # initial log level TRACE, DEBUG, INFO, WARN, ERROR
TRACE_SYSCALLS=0    # to trace all syscalls
TRACE_IPC=0         # to trace IPC between processes

# other filesystem options, supported formats, init ram disk, sizes, etc.
# various drivers support options, (hardware, fs, network, cpu features, debugging etc)

# memory and disk mapping
SECTOR_SIZE=512

STAGE1_SIZE=$SECTOR_SIZE    # one sector, this size preset by BIOS
STAGE1_LOAD_ADDRESS=0x7C00  # at 31KB, this address preset by BIOS
STAGE1_STACK_TOP=0x0000     # no stack used on 1st stage
STAGE1_SECTOR_COUNT=$(($STAGE1_SIZE / $SECTOR_SIZE))
STAGE1_FIRST_SECTOR=0

STAGE2_SIZE_KB=12           # 12 KB currently, can go up to 29 KB
STAGE2_LOAD_ADDRESS=0x0800  # at 2 KB, to clear IVT, BIOS memory area etc.
STAGE2_STACK_TOP=0x7C00     # at 31KB, right below stage 1
STAGE2_SECTOR_COUNT=$(($STAGE2_SIZE_KB * 1024 / $SECTOR_SIZE))
STAGE2_FIRST_SECTOR=$(($STAGE1_SECTOR_COUNT))

KERNEL_SIZE_KB=192          # can go up to 608 KB, but keep an eye for stack!
KERNEL_LOAD_ADDRESS=0x8000  # at 32KB, below upper memory (640KB), must be < 1MB, to be loaded in real mode.
KERNEL_STACK_TOP=0x90000    # at 576KB, below upper memory
KERNEL_SECTOR_COUNT=$(($KERNEL_SIZE_KB * 1024 / $SECTOR_SIZE))
KERNEL_FIRST_SECTOR=$(($STAGE1_SECTOR_COUNT + $STAGE2_SECTOR_COUNT))
KERNEL_HEAP_ADDRESS=0x100000 # at 1MB, to clear upper memory
KERNEL_HEAP_SIZE_KB=4096
KERNEL_RAMDISK_ADDRESS=$(($KERNEL_HEAP_ADDRESS + 1024 * $KERNEL_HEAP_SIZE_KB))
KERNEL_RAMDISK_SIZE_KB=2048

# image size and filesystem partitions
DISK_IMAGE_SIZE_MB=8
DISK_IMAGE_SIZE_BYTES=$(($DISK_IMAGE_SIZE_MB * 1024 * 1024))
DISK_IMAGE_SECTOR_COUNT=$(($DISK_IMAGE_SIZE_BYTES / $SECTOR_SIZE))
PARTITION_1_FIRST_SECTOR=$(($KERNEL_FIRST_SECTOR + $KERNEL_SECTOR_COUNT))
PARTITION_1_SECTOR_COUNT=$(($DISK_IMAGE_SECTOR_COUNT - $PARTITION_1_FIRST_SECTOR))

# -------------------------------------------------

echo Creating configuration included files...


cat > config.mk <<EOF
# do not edit, run configure.sh to generate
CROSS_CC                 := $CROSS_CC
CROSS_LD                 := $CROSS_LD
CROSS_AS                 := $CROSS_AS
VERSION                  := $VERSION
GIT_HASH                 := $GIT_HASH
DATE_BUILT               := $DATE_BUILT
STAGE1_LOAD_ADDRESS      := $STAGE1_LOAD_ADDRESS
STAGE1_STACK_TOP         := $STAGE1_STACK_TOP
STAGE1_SIZE              := $STAGE1_SIZE
STAGE1_FIRST_SECTOR      := $STAGE1_FIRST_SECTOR
STAGE1_SECTOR_COUNT      := $STAGE1_SECTOR_COUNT
STAGE2_LOAD_ADDRESS      := $STAGE2_LOAD_ADDRESS
STAGE2_STACK_TOP         := $STAGE2_STACK_TOP
STAGE2_SIZE_KB           := $STAGE2_SIZE_KB
STAGE2_FIRST_SECTOR      := $STAGE2_FIRST_SECTOR
STAGE2_SECTOR_COUNT      := $STAGE2_SECTOR_COUNT
KERNEL_LOAD_ADDRESS      := $KERNEL_LOAD_ADDRESS
KERNEL_STACK_TOP         := $KERNEL_STACK_TOP
KERNEL_SIZE_KB           := $KERNEL_SIZE_KB
KERNEL_FIRST_SECTOR      := $KERNEL_FIRST_SECTOR
KERNEL_SECTOR_COUNT      := $KERNEL_SECTOR_COUNT
KERNEL_HEAP_ADDRESS      := $KERNEL_HEAP_ADDRESS
KERNEL_HEAP_SIZE_KB      := $KERNEL_HEAP_SIZE_KB
KERNEL_RAMDISK_ADDRESS   := $KERNEL_RAMDISK_ADDRESS
KERNEL_RAMDISK_SIZE_KB   := $KERNEL_RAMDISK_SIZE_KB
SECTOR_SIZE              := $SECTOR_SIZE
DISK_IMAGE_SIZE_MB       := $DISK_IMAGE_SIZE_MB
DISK_IMAGE_SIZE_BYTES    := $DISK_IMAGE_SIZE_BYTES
DISK_IMAGE_SECTOR_COUNT  := $DISK_IMAGE_SECTOR_COUNT
PARTITION_1_FIRST_SECTOR := $PARTITION_1_FIRST_SECTOR
PARTITION_1_SECTOR_COUNT := $PARTITION_1_SECTOR_COUNT
EOF


cat > config.h <<EOF
#pragma once
// do not edit, run configure.sh to generate
#define VERSION                   "$VERSION"
#define GIT_HASH                  "$GIT_HASH"
#define DATE_BUILT                "$DATE_BUILT"
#define STAGE1_LOAD_ADDRESS       $STAGE1_LOAD_ADDRESS
#define STAGE1_STACK_TOP          $STAGE1_STACK_TOP
#define STAGE1_SIZE               $STAGE1_SIZE
#define STAGE1_FIRST_SECTOR       $STAGE1_FIRST_SECTOR
#define STAGE1_SECTOR_COUNT       $STAGE1_SECTOR_COUNT
#define STAGE2_LOAD_ADDRESS       $STAGE2_LOAD_ADDRESS
#define STAGE2_STACK_TOP          $STAGE2_STACK_TOP
#define STAGE2_SIZE_KB            $STAGE2_SIZE_KB
#define STAGE2_FIRST_SECTOR       $STAGE2_FIRST_SECTOR
#define STAGE2_SECTOR_COUNT       $STAGE2_SECTOR_COUNT
#define KERNEL_LOAD_ADDRESS       $KERNEL_LOAD_ADDRESS
#define KERNEL_STACK_TOP          $KERNEL_STACK_TOP
#define KERNEL_SIZE_KB            $KERNEL_SIZE_KB
#define KERNEL_FIRST_SECTOR       $KERNEL_FIRST_SECTOR
#define KERNEL_SECTOR_COUNT       $KERNEL_SECTOR_COUNT
#define KERNEL_HEAP_ADDRESS       $KERNEL_HEAP_ADDRESS
#define KERNEL_HEAP_SIZE_KB       $KERNEL_HEAP_SIZE_KB
#define KERNEL_RAMDISK_ADDRESS    $KERNEL_RAMDISK_ADDRESS
#define KERNEL_RAMDISK_SIZE_KB    $KERNEL_RAMDISK_SIZE_KB
#define SECTOR_SIZE               $SECTOR_SIZE
#define DISK_IMAGE_SIZE_MB        $DISK_IMAGE_SIZE_MB
#define DISK_IMAGE_SIZE_BYTES     $DISK_IMAGE_SIZE_BYTES
#define DISK_IMAGE_SECTOR_COUNT   $DISK_IMAGE_SECTOR_COUNT
#define PARTITION_1_FIRST_SECTOR  $PARTITION_1_FIRST_SECTOR
#define PARTITION_1_SECTOR_COUNT  $PARTITION_1_SECTOR_COUNT
EOF


cat > config.sh <<EOF
#!/bin/sh
# do not edit, run configure.sh to generate
VERSION="$VERSION"
GIT_HASH="$GIT_HASH"
DATE_BUILT="$DATE_BUILT"
STAGE1_LOAD_ADDRESS=$STAGE1_LOAD_ADDRESS
STAGE1_STACK_TOP=$STAGE1_STACK_TOP
STAGE1_SIZE=$STAGE1_SIZE
STAGE1_FIRST_SECTOR=$STAGE1_FIRST_SECTOR
STAGE1_SECTOR_COUNT=$STAGE1_SECTOR_COUNT
STAGE2_LOAD_ADDRESS=$STAGE2_LOAD_ADDRESS
STAGE2_STACK_TOP=$STAGE2_STACK_TOP
STAGE2_SIZE_KB=$STAGE2_SIZE_KB
STAGE2_FIRST_SECTOR=$STAGE2_FIRST_SECTOR
STAGE2_SECTOR_COUNT=$STAGE2_SECTOR_COUNT
KERNEL_LOAD_ADDRESS=$KERNEL_LOAD_ADDRESS
KERNEL_STACK_TOP=$KERNEL_STACK_TOP
KERNEL_SIZE_KB=$KERNEL_SIZE_KB
KERNEL_FIRST_SECTOR=$KERNEL_FIRST_SECTOR
KERNEL_SECTOR_COUNT=$KERNEL_SECTOR_COUNT
KERNEL_HEAP_ADDRESS=$KERNEL_HEAP_ADDRESS
KERNEL_HEAP_SIZE_KB=$KERNEL_HEAP_SIZE_KB
KERNEL_RAMDISK_ADDRESS=$KERNEL_RAMDISK_ADDRESS
KERNEL_RAMDISK_SIZE_KB=$KERNEL_RAMDISK_SIZE_KB
SECTOR_SIZE=$SECTOR_SIZE
DISK_IMAGE_SIZE_MB=$DISK_IMAGE_SIZE_MB
DISK_IMAGE_SIZE_BYTES=$DISK_IMAGE_SIZE_BYTES
DISK_IMAGE_SECTOR_COUNT=$DISK_IMAGE_SECTOR_COUNT
PARTITION_1_FIRST_SECTOR=$PARTITION_1_FIRST_SECTOR
PARTITION_1_SECTOR_COUNT=$PARTITION_1_SECTOR_COUNT
EOF
