#include "./include/ctypes.h"
#include "./include/bits.h"
#include "utils/panic.h"
#include "arch/gdt.h"
#include "arch/idt.h"
#include "arch/pic.h"
#include "arch/cpu.h"
#include "drivers/screen.h"
#include "drivers/timer.h"
#include "drivers/clock.h"
#include "drivers/serial.h"
#include "devices/tty.h"
#include "memory/virtmem.h"
#include "memory/kheap.h"
#include "logger/logger.h"
#include "logger/mem_log.h"
#include "utils/kcmd_line_args.h"
#include "klib/string.h"
#include "memory/physmem.h"
#include "memory/mem_region.h"

#include "devices/devices.h"
#include "devices/pci/pci_device.h"
#include "devices/block/block_device.h"
#include "devices/block/ata_block_device.h"
#include "devices/block/sata_block_device.h"
#include "devices/block/ram_block_device.h"

#include "filesys/fs_api.h"
#include "filesys/vfs_api.h"
#include "filesys/partitions/legacy_partition.h"
#include "filesys/partitions/uefi_partition.h"
#include "filesys/fs_drivers/skeleton_fs/skeleton_fs.h"
#include "filesys/fs_drivers/sfs/sfs.h"
#include "filesys/dev_drivers/tty/dev_tty.h"

#include "proc/semaphore.h"
#include "proc/multitask.h"
#include "proc/process/process.h"
#include "proc/spawn.h"

#include "tasks/monitor.h"
#include "../stage2/boot_info.h" // bootinfo pointer is passed from 2nd stage
#include "../config.h"           // compilation configuration generated by configure.sh



// Check if the compiler thinks you are targeting the wrong operating system.
#if defined(__linux__)
    #error "You are not using a cross-compiler, you will most certainly run into trouble"
#endif

// This tutorial will only work for the 32-bit ix86 targets.
#if !defined(__i386__)
    #error "This tutorial needs to be compiled with a ix86-elf compiler"
#endif

#if !defined(__KERNEL__)
    #error "To compile for kernel the __KERNEL__ macro must be defined"
#endif

MODULE("MAIN", LOG_LEVEL_INFO);



static void launch_initial_process();
static void shell_launcher();
static void initialize_physical_memory(boot_info_t *info);
static void initialize_storage_and_file_systems();
static void print_stage2_boot_info(boot_info_t *info);

boot_info_t saved_multiboot_info;
mem_map_t kernel_phys_mem_map;



void kernel_main(boot_info_t* boot)
{
    // interrupts are disabled, nmi is also disabled
    // to allow us to set up our Interrupt Table

    // initialize in-memory log
    init_logger();
    logger_set_global_minimum_log_level(LOG_LEVEL_INFO);
    logger_add_appender(mem_log_appender, NULL, LOG_LEVEL_TRACE);

    // initialize screen and allow logs to be written to it
    screen_init();
    panic_set_writer(screen_panic_writer);
    logger_add_appender(screen_log_appender, NULL, LOG_LEVEL_TRACE);
    
    log_info("Kernel starting");
    log_info("Version %s, (%s), built %s", VERSION, GIT_HASH, DATE_BUILT);

    print_stage2_boot_info(boot);
    memcpy((char *)&saved_multiboot_info, (char *)boot, sizeof(boot_info_t));
    kcmd_parse(saved_multiboot_info.cmdline);

    log_info("Initializing Global Descriptor Table...");
    // kernel code segment selector: 0x08 (8)
    // kernel data segment selector: 0x10 (16)
    init_gdt();

    log_info("Initializing Interrupts Descriptor Table...");
    init_idt(0x8);

    log_info("Initializing Programmable Interrupt Controller...");
    init_pic();

    log_info("Initializing Programmable Interval Timer...");
    init_timer();

    log_info("Initializing Real Time Clock...");
    init_real_time_clock(15);

    log_info("Initializing Physical Memory Manager...");
    initialize_physical_memory(boot);

    log_info("Initializing Serial Port 1 for logging...");
    init_serial_port();

    log_info("Switching logging to serial port");
    panic_set_writer(serial_panic_writer);
    logger_add_appender(serial_log_appender, NULL, LOG_LEVEL_TRACE);
    
    log_info("Initializing Kernel Heap...");
    init_kernel_heap((void *)KERNEL_HEAP_ADDRESS, KERNEL_HEAP_SIZE_KB * 1024);

    log_info("Initializing virtual memory mapping...");
    phys_addr_t max_used_address = pmm_get_top_identity_address();
    vmm_initialize(0, max_used_address, 16 * MB, KERNEL_UTIL_PAGES_ADDRESS, KERNEL_UTIL_PAGES_SIZE_KB * 1024, &kernel_phys_mem_map);

    log_info("Enabling interrupts & NMI...");
    sti();
    enable_nmi();

    log_info("Detecting PCI devices...");
    discover_all_pci_devices();
    log_all_pci_devices();

    log_info("Initializing file system...");
    initialize_storage_and_file_systems();

    log_info("Initializing multi-tasking...");
    init_multitasking();

    log_info("Giving the console to TTY manager...");
    logger_remove_appender(screen_log_appender, NULL);
    init_tty_manager(7, 100);
    fs_register_device("tty0", &tty_dev_driver, 0);
    fs_register_device("tty1", &tty_dev_driver, 1);
    fs_register_device("tty2", &tty_dev_driver, 2);
    fs_register_device("tty3", &tty_dev_driver, 3);
    fs_register_device("tty4", &tty_dev_driver, 4);
    fs_register_device("tty5", &tty_dev_driver, 5);
    tty_t *log_tty = tty_manager_get_device(6);
    tty_set_title_specific_tty(log_tty, "System log");
    logger_add_appender(tty_log_appender, log_tty, LOG_LEVEL_INFO);

    // create desired tasks here (init, logic, sh, etc)
    launch_initial_process();

    // start_multitasking() will never return
    log_info("Starting multitasking, goodbye from main()!");
    start_multitasking();
    panic("start_multitasking() returned to main");
}

static void launch_initial_process() {
    
    process_t *proc;
    error_t err = process_v2_create_for_spawn(NULL, "/bin/init", PRIORITY_USER_PROGRAM, &proc);
    if (err) panic("Cannot create init process: %s", strerror(err));

    log_info_fmt("init: ", proc, proc_log_formatter);
    proc_start(proc);
}

// these are defined in the linker.ld script
// use their *addresses*, not their values!
extern char _linker_start_address[];
extern char _segment_text_start[];
extern char _segment_text_end[];
extern char _segment_rodata_start[];
extern char _segment_rodata_end[];
extern char _segment_init_data_start[];
extern char _segment_init_data_end[];
extern char _segment_zero_data_start[];
extern char _segment_zero_data_end[];
extern char _linker_end_address[];


static void initialize_physical_memory(boot_info_t *info) {

    // find highest memory address of machine, cap at 4GB
    uint64_t machine_max_memory_64 = 0;
    for (uint32_t i = 0; i < info->mem.count; i++) {
        uint64_t entry_top64 = info->mem.entries[i].base + info->mem.entries[i].length;
        if (entry_top64 > machine_max_memory_64)
            machine_max_memory_64 = entry_top64;
    }

    // this variable must be static, we are well before initializing heap...
    // notice that IVT, VGA, FB, don't _have_ to be identity matching, as long as any virtual address resolves to the correct physical one.
    kernel_phys_mem_map = (mem_map_t){ .count = 0, .name = "Kernel physical memory map" };
    mem_map_add_region(&kernel_phys_mem_map, mem_region_kernel_other(0, 4096, "ivt_bios"));
    mem_map_add_region(&kernel_phys_mem_map, mem_region_kernel_code((phys_addr_t)&_segment_text_start, (size_t)(_segment_text_end - _segment_text_start)));
    mem_map_add_region(&kernel_phys_mem_map, mem_region_kernel_rodata((phys_addr_t)&_segment_rodata_start, (size_t)(_segment_rodata_end - _segment_rodata_start)));
    mem_map_add_region(&kernel_phys_mem_map, mem_region_kernel_data((phys_addr_t)&_segment_init_data_start, (size_t)(_segment_init_data_end- _segment_init_data_start)));
    mem_map_add_region(&kernel_phys_mem_map, mem_region_kernel_bss((phys_addr_t)&_segment_zero_data_start, (size_t)(_segment_zero_data_end - _segment_zero_data_start)));
    mem_map_add_region(&kernel_phys_mem_map, mem_region_kernel_stack((phys_addr_t)_segment_zero_data_end, (size_t)(KERNEL_STACK_TOP - (size_t)&_segment_zero_data_end)));
    mem_map_add_region(&kernel_phys_mem_map, mem_region_kernel_other((phys_addr_t)KERNEL_UTIL_PAGES_ADDRESS, (size_t)KERNEL_UTIL_PAGES_SIZE_KB * 1024, "util_page"));
    mem_map_add_region(&kernel_phys_mem_map, mem_region_kernel_other(640*1024, (1024-640)*1024, "low_mem"));
    mem_map_add_region(&kernel_phys_mem_map, mem_region_kernel_other((phys_addr_t)KERNEL_RAMDISK_ADDRESS, (size_t)KERNEL_RAMDISK_SIZE_KB * 1024, "ramdisk"));
    mem_map_add_region(&kernel_phys_mem_map, mem_region_kernel_heap((phys_addr_t)KERNEL_HEAP_ADDRESS, (size_t)KERNEL_HEAP_SIZE_KB * 1024));
    log_info_fmt("", &kernel_phys_mem_map, mem_map_formatter);

    // where physical memory mapper can put its bitmap
    uintptr_t kernel_top_address = mem_map_get_top_address(&kernel_phys_mem_map);

    log_info("Machine maximum memory address 0x%08x.%08x (%u KB, %u MB, %u GB)",
        (uint32_t)(machine_max_memory_64 >> 32),
        (uint32_t)(machine_max_memory_64 & 0xFFFFFFFF),
        (uint32_t)(machine_max_memory_64 / 1024),
        (uint32_t)(machine_max_memory_64 / (1024 * 1024)),
        (uint32_t)(machine_max_memory_64 / (1024 * 1024 * 1024))
    );
    log_info("Kernel area topmost address 0x%08x", kernel_top_address);

    pmm_initialize(machine_max_memory_64, kernel_top_address);
    for (uint32_t i = 0; i < info->mem.count; i++) {
        e820_memory_entry *entry = &info->mem.entries[i];
        pmm_mark_region_available((phys_addr_t)entry->base, (size_t)entry->length);
    }
    pmm_mark_region_reserved((phys_addr_t)0, (size_t)kernel_top_address);
    pmm_finish_initialization();

    log_info("Physical memory manager initialized. %u total pages, %u (%u MB or %u%%) reserved, %u (%u MB or %u%%) available",
        pmm_total_pages(),
        pmm_used_pages(),
        (pmm_used_pages() * 4) / 1024,
        pmm_total_pages() == 0 ? 0 : (pmm_used_pages() * 100) / pmm_total_pages(),
        pmm_free_pages(),
        (pmm_free_pages() * 4) / 1024,
        pmm_total_pages() == 0 ? 0 : (pmm_free_pages() * 100) / pmm_total_pages()
    );

    pmm_debug_bitmap_ranges();
}

static void print_stage2_boot_info(boot_info_t *info) {
    log_info("boot_info from stage 2 (ptr address 0x%08x)", info);
    log_info("- kernel cmd line: \"%s\"", info->cmdline);
    log_info("- machine memory map (total of %u entries)", info->mem.count);
    log_info("    No              Address               Length  Type  ACPI");
    //             00  0x12345678-12345678  0x12345678-12345678  1234  1234
    for (uint32_t i = 0; i < info->mem.count; i++) {
        e820_memory_entry *mm = &info->mem.entries[i];
        log_info("    %2u  0x%08x-%08x  0x%08x-%08x  %4u  %4u", 
            i,
            HIGH_DWORD(mm->base), LOW_DWORD(mm->base),
            HIGH_DWORD(mm->length), LOW_DWORD(mm->length),
            mm->type, 
            mm->acpi_ext);
    }
    log_info("- VBE framebuffer at 0x%08x-%08x, %u x %u x %u, pitch %u", 
        HIGH_DWORD(info->fb.fb_addr),
        LOW_DWORD(info->fb.fb_addr),
        info->fb.width,
        info->fb.height,
        info->fb.bpp,
        info->fb.pitch);
}

static void initialize_storage_and_file_systems() {
    error_t err;
    int count;
    block_device_t *dev;


    // iterate over discovered PCI devs, instantiate & register devices
    discover_and_register_all_ata_block_devices(&pci_devices_list);
    discover_and_register_all_sata_block_devices(&pci_devices_list);

    list_foreach(&block_devices_list, block_device_t, dev) {
        discover_and_register_legacy_partition_block_devices(dev);
        discover_and_register_uefi_partition_block_devices(dev);
    }

    // here, optionally add the ram disk
    if (KERNEL_RAMDISK_SIZE_KB > 0) {
        create_ram_block_device("rd", "Ram Disk", 512, KERNEL_RAMDISK_SIZE_KB * (1024 / 512), (char *)KERNEL_RAMDISK_ADDRESS, &dev);
        list_append(&block_devices_list, dev);
    }

    // now that we finished...
    log_all_block_devices();


    // here, iterate over devices, discover partitions, append them to the same list.
    // maybe append the ramdisk as well, if any
    // then probe filesystems to see if anything is mountable
    // also, parse cmd line to discover which disk/partition to mount as root
    const char *root = kcmd_get("root");
    if (root == NULL) {
        //try for the first one?
        log_warn("No root device found in kernel cmd line. Pass 'root=hdx' to define root device or partition");
    } else {
        // find if not found...
        log_warn("Root device '%s' from kernel cmd line not found");
    }

    // register filesystems
    fs_register(&simple_fs);

    // let's go with the first, first.
    bool mounted_one = false;
    list_foreach(&block_devices_list, block_device_t, dev) {
        fs_driver_t *driver = fs_probe(dev);
        if (driver == NULL)
            continue;
        
        log_info("Mounting device %s as root using driver '%s'", dev->id, driver->name);
        err = vfs_mount("/", dev, driver->ops);
        if (err) {
            log_error("Mount device %s by driver %s failed: %d", dev->id, driver->name, err);
            continue;
        }

        mounted_one = true;
        break;
    }

    if (!mounted_one)
        panic("Could not mount a root device");
}