#include "../include/ctypes.h"
#include "../klib/string.h"
#include "../logger/logger.h"
#include "../drivers/serial.h"

MODULE("BACKTRACE", LOG_LEVEL_TRACE);


// this one is generated by linker, inside makefile
extern struct symbol { uint32_t addr; const char *name; } g_symbol_table[];


// defining a "weak" empty table, so that pass 1 will link with empty array.
// pass 2 will find the real one in kernel_symbols.o and override this.
__attribute__((weak)) struct symbol g_symbol_table[] = { {0, (void*)0} };


extern struct symbol _k_symtab_start[];
extern struct symbol _k_symtab_end[];

const char* kdebug_get_symbol(uint32_t addr) {
    const char* name = "unknown";

    log_debug("ksym: start=%p, end=%p, size=%d, count=%d", _k_symtab_start, _k_symtab_end, _k_symtab_end - _k_symtab_start, (_k_symtab_end - _k_symtab_start) / sizeof(struct symbol));
    
    // Calculate how many actual elements are in the memory region
    // between the two linker-defined addresses.
    size_t total = ((uintptr_t)&_k_symtab_end - (uintptr_t)&_k_symtab_start) / sizeof(struct symbol);

    for (size_t i = 0; i < total; i++) {
        // Use the start pointer directly
        struct symbol *s = &_k_symtab_start[i];
        log_debug("symbols[%i] (at %p) = { %p, \"%s\" }", i, s, s->addr, s->name);

        if (s->addr > addr)
            break;

        name = s->name;
    }

    return name;
}

// Represents the physical layout of an i686 stack frame
struct stack_frame {
    struct stack_frame* next_ebp;
    uint32_t return_addr;
};

void kdebug_backtrace() {
    struct stack_frame *curr;

    // Inline assembly to capture the current EBP register
    // since EBP is pointing to the prev frame,
    // the first function to appear will be the one that CALLED the backtrace()
    asm volatile("mov %%ebp, %0" : "=r"(curr));

    log_info("--- Kernel stack trace ---");
    while (curr != NULL) {
        uint32_t addr = curr->return_addr;

        // we subtract one to get BEFORE the address after the call.
        // remember, it's the address AFTER the call that is being pushed
        const char* name = kdebug_get_symbol(addr - 1);

        log_info("    0x%08x: %s()", addr, name);

        struct stack_frame *next = curr->next_ebp;
        if (next == NULL)  // was it the last frame?
            break;
        else if ((uint32_t)next > KERNEL_STACK_TOP)  // we got out of stack
            break;
        else if ((uint32_t)next & 0x03) {  // stack frames must be aligned on 4 bytes on i686
            log_info("    Error: Unaligned frame pointer 0x%08x", (uint32_t)next);
            break;
        }
        if (next <= curr)
            break;

        curr = next;
    }
    log_info("--- End of trace ---");
}

