# $Id: Makefile.config.in,v 1.5 2025/10/22 23:20:41 sjg Exp $

DIFF_FLAGS?= -u
EGREP= egrep
LUA?= 
TOOL_DIFF?= diff
UTC_1= Europe/Berlin
srcdir= /home/dimitris/code/handcrafted-os/nursery/build-attempt3/userapps/bmake/unit-tests
