#include "../include/ctypes.h"
#include "../klib/string.h"
#include "../logger/logger.h"
#include "../drivers/serial.h"

MODULE("BACKTRACE", LOG_LEVEL_TRACE);


// this one is generated by linker, inside makefile
extern struct symbol { uint32_t addr; const char *name; } g_symbol_table[];


// defining a "weak" empty table, so that pass 1 will link with empty array.
// pass 2 will find the real one in kernel_symbols.o and override this.
__attribute__((weak)) struct symbol g_symbol_table[] = { {0, (void*)0} };


extern struct symbol _k_symtab_start[];
extern struct symbol _k_symtab_end[];

const char* kdebug_get_symbol(uint32_t addr) {
    const char* name = "unknown";
    
    // Calculate how many actual elements are in the memory region
    // between the two linker-defined addresses.
    size_t total = ((uintptr_t)&_k_symtab_end - (uintptr_t)&_k_symtab_start) / sizeof(struct symbol);

    for (size_t i = 0; i < total; i++) {
        // Use the start pointer directly
        struct symbol *s = &_k_symtab_start[i];

        if (s->addr > addr)
            break;

        name = s->name;
    }

    return name;
}

// Represents the physical layout of an i686 stack frame
struct stack_frame {
    struct stack_frame* next_ebp;
    uint32_t return_addr;
};

void kdebug_backtrace() {
    struct stack_frame *curr;

    // Inline assembly to capture the current EBP register
    // since EBP is pointing to the prev frame,
    // the first function to appear will be the one that CALLED the backtrace()
    asm volatile("mov %%ebp, %0" : "=r"(curr));

    log_info("--- Kernel stack trace ---");
    while (curr != NULL) {
        uint32_t addr = curr->return_addr;

        // we subtract one to get BEFORE the address after the call.
        // remember, it's the address AFTER the call that is being pushed
        const char* name = kdebug_get_symbol(addr - 1);

        log_info("    0x%08x: %s()", addr, name);

        struct stack_frame *next = curr->next_ebp;
        if (next == NULL)  // was it the last frame?
            break;
        else if ((uint32_t)next > KERNEL_STACK_TOP)  // we got out of stack
            break;
        else if ((uint32_t)next & 0x03) {  // stack frames must be aligned on 4 bytes on i686
            log_info("    Error: Unaligned frame pointer 0x%08x", (uint32_t)next);
            break;
        }
        if (next <= curr)
            break;

        curr = next;
    }
    log_info("--- End of trace ---");
}

// ----------------------------------
#define SHELL_SERIAL_PORT  0

static bool finished(char **cmd_ptr) {
    return (**cmd_ptr == 0);
}
static void skip_whitespace(char **cmd_ptr) {
    while (**cmd_ptr == ' ')
        (*cmd_ptr) += 1;
}
static void get_str_argument(char **cmd_ptr, char *buff, int buff_size) {
    skip_whitespace(cmd_ptr);
    buff[0] = 0;
    int i = 0;
    while (**cmd_ptr != ' ' && **cmd_ptr != '\0' && i < buff_size - 1) {
        buff[i++] = **cmd_ptr;
        (*cmd_ptr) += 1;
    }
    buff[i] = 0;
}
static uint32_t get_num_argument(char **cmd_ptr) {
    char buff[32];
    skip_whitespace(cmd_ptr);
    get_str_argument(cmd_ptr, buff, sizeof(buff));
    return atoui(buff);
}
static bool matches(char **cmd_ptr, char *prefix) {
    skip_whitespace(cmd_ptr);
    int len = strlen(prefix);
    if (memcmp(*cmd_ptr, prefix, len) != 0)
        return false;
    
    (*cmd_ptr) += len;
    return true;
}
static void shprintf(const char *fmt, ...) {
    char buff[128];
    va_list args;
    va_start(args, fmt);
    vsprintfn(buff, sizeof(buff), fmt, args);
    va_end(args);
    serial_write(SHELL_SERIAL_PORT, buff);
}

static void shell_hd(char *args) {
    uint32_t addr = finished(&args) ? 0 : get_num_argument(&args);
    uint32_t size = finished(&args) ? 16 : get_num_argument(&args);
    shprintf("Hex dump, addr = 0x%08x, size = %d\n", addr, size);
    log_debug_hex((void *)addr, size, addr);
}
static void shell_sym(char *args) {
    uint32_t addr = finished(&args) ? 0 : get_num_argument(&args);
    shprintf("Symbol at %p: %s\n", addr, kdebug_get_symbol(addr));
}

struct shell_cmd {
    char *prefix;
    char *description;
    void (*func)(char *rest);
};
static struct shell_cmd cmds[] = {
    { "exit", "exits the shell", NULL },
    { "help", "lists available commands", NULL },
    { "hd", "hd <addr> [<size>]   hex dumps a portion of memory.", shell_hd },
    { "sym", "sym <addr>          prints kernel symbol name", shell_sym },
};

static bool get_cmd(char *buffer, int buffer_size) {
    while (true) {
        serial_write(SHELL_SERIAL_PORT, "kernel shell > ");
        serial_wait_gets(SHELL_SERIAL_PORT, buffer, buffer_size);
        if (strlen(buffer) == 0) continue;
        if (strcmp(buffer, "exit") == 0) return false;
        return true;
    }
}
void kshell() {
    char cmd[128];
    char text[128];
    char *ptr;
    int num_cmds = sizeof(cmds) / sizeof(cmds[0]);

    while (1) {
        if (!get_cmd(cmd, sizeof(cmd)))
            break;

        if (strcmp(cmd, "help") == 0) {
            for (int i = 0; i < num_cmds; i++)
                shprintf("  %-10s %s\n", cmds[i].prefix, cmds[i].description);
            continue;
        }

        ptr = cmd;
        bool cmd_found = false;
        for (int i = 0; i < num_cmds; i++) {
            if (!matches(&ptr, cmds[i].prefix))
                continue;
            cmd_found = true;
            skip_whitespace(&ptr);
            cmds[i].func(ptr);
            break;
        }

        if (!cmd_found)
            shprintf("cmd '%s' not found, 'help' for available commands\n", cmd);
    }
}